project:
  type: book

book:
  title: "Marine Sensitivities Tech Docs"
  author: "Ben Best"
  date: today
  repo-url: https://github.com/MarineSensitivities/docs/
  repo-actions: [edit]
  downloads: [pdf, docx]
  sharing: [twitter, facebook]
  chapters:
    - index.qmd
    - intro.qmd
    - part: components.qmd
      chapters:
        - components/server.qmd
        - components/workflows.qmd
        - components/libraries.qmd
        - components/api.qmd
        - components/apps.qmd
        - components/docs.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  docx:
    toc: true
    number-sections: true
    highlight-style: github



