project:
  type: book
  output-dir: _book
  resources:
  - "/.nojekyll"

book:
  title: "Marine Sensitivity"
  subtitle: "Marine Sensitivity Documentation"
  author: "Ben Best"
  date: today
  date-format: "YYYY-MM-DD"
  repo-url: https://github.com/MarineSensitivity/docs/
  repo-actions: [edit]
  downloads: [docx]
  sharing: [twitter, facebook]
  # google-analytics: "G-V3HZN14Z8G" # TODO: add Google Analytics
  search: true
  page-navigation: true
  page-footer:
    left: |
      © <a href="https://bbest.github.io/cv/"  target="_blank">Ben Best</a>,
      <a href="https://www.boem.gov/environment/environmental-studies/environmental-studies-information"  target="_blank">BOEM-ESP</a>
    right: |
      Built with <a href="https://quarto.org/" target="_blank">Quarto</a>
  chapters:
    - index.qmd
    - intro.qmd
    - part: science.qmd
      chapters:
        - stressors.qmd
        - receptors.qmd
        - exposure.qmd
    - part: software.qmd
      chapters:
        - server.qmd
        - db.qmd
        - workflows.qmd
        - apis.qmd
        - libraries.qmd
        - apps.qmd
        - docs.qmd
    - summary.qmd
    - references.qmd
  appendices:
    - glossary.qmd
    - part: apps.qmd
      chapters:
        - apps/vmap.qmd
        - apps/sdm-cog.qmd
        - apps/sdm.qmd
        - apps/aoi.qmd
        - apps/bird_hotspots.qmd
        - apps/map.qmd


bibliography: references.bib

format:
  html:
    theme: cosmo
    css: glossary/glossary.css
    echo: false
  # pdf:
  #   documentclass: scrreprt
  docx:
    toc: true
    echo: false
    number-sections: true
    highlight-style: github



